services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    networks:
      - leaderboard_net
    command: postgres -N 500
    ports:
      - 5432:5432
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - type: tmpfs
        target: /var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - leaderboard_net

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=redis
      - HTTP_PASSWORD=redis
    ports:
      - 8081:8081
    networks:
      - leaderboard_net
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  leaderboard_net:
    name: leaderboard_net
